config/routes.rb
MyPage::Application.routes.draw do
  

  root "my_page#home"
  match "/find", to: "my_page#find", via: 'get'
  match "/contact", to: "my_page#contact", via: 'get'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/my_page_controller.rb
class MyPageController < ApplicationController
  def home
  end

  def find
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :date, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
      base_title = "Dinorah"
      if page_title.empty?
        base_title
      else 
        "#{base_title} | #{page_title}"
      end
    end
    
    def link_to_image(image_path, target_link,options={})
      link_to(image_tag(image_path), target_link, options)
    end
    
end

app/helpers/my_page_helper.rb
module MyPageHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top" role ="navigation">
     	 
     	<div class = "navbar-collapse collapse">
		<ul class = "nav navbar-nav">
			<li> <%= link_to "Home", root_path %> </li>

			<li> <%= link_to "Find me and my code", find_path  %> </li>

			 
		</ul>

	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    
	<%= render '/layouts/header' %>	
	<%= yield %>
    <%= render '/layouts/footer'%>
   
</body>
</html>

app/views/my_page/find.html.erb
<% provide(:title, 'Find Me')%>

<div class = "findMe">
	<div id= "main">   
	<div class = "icon"> 
	 <%= link_to_image('linkedin.png', 'http://www.linkedin.com/pub/dinorah-carrion/31/6b2/16b')%> 
	 <%= link_to_image('GitHub-Mark-120px-plus.png', 'https://github.com/DinorahCr/')%> 
	 <%= link_to_image('gmail-64.png', 'mailto:dcarrion@uci.edu')%> 
	</div>
	</div>
</div>

app/views/my_page/home.html.erb
<% provide(:title, 'Home')%>
<%= javascript_include_tag "home" %>
<div class = "row">
	<div class="container-fluid">
	<div class = "col-md-6 col-md-offset-3">
		<div class = "info-box">
			<h2> Hello, I am Dinorah</h2>
			<p> Computer Science undergrad at University of California, Irvine </p>
			<p> Gates Millennium Scholar </p>
			<p> Fluent in: Spanish, English, <code>Java, Python, Ruby on Rails</code>  
				[working on C++, JavaScript]</p>
			<p> I specially like data mining, web dev, and informatics </p>
		    <p id = "trope"> >> This is what my friends think I do when I'm coding. Coincidentally, how I would look as
			 a 90s movie hacker 
			</p> 
		         
		         <div id = "modalImage">
					<div id = "me"> <%= image_tag('trope.png', size: "600") %> </div>
					<p id = "caption"> Totally, broke into the mainframe and the firewall. Woo! Hack all the servers! </p>
				</div>
			
		   <p> Oh, and I'm from Puerto Rico but currently living in California</p>
		</div>
		
	        <next>
			<%= link_to 'Code', find_path%> 
		    <span class="glyphicon glyphicon-chevron-down" style = "color:black"></span> 
			</next>
		
	</div>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<post>

	<div id="left"> </div>
	<div id="right"></div>
	<div id="top"></div>
	<div id="bottom"></div>
    
    <% @posts.each do |post| %>
      
        <%= post.description %>
        <%= post.date %>
        <%= post.image %>
        <%= link_to 'Show', post %>
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
   
    <% end %>
 

<br>
</post>
<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @post.date %>
</p>

<p>
  <strong>Image:</strong>
  <%= @post.image %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>